---
title: "An updated R introduction"
author: "Alejandro Pulver"
date: "04/12/2014"
output:
  html_document:
    toc: true
---

# Installation

In Ubuntu, R can be installed with `sudo apt-get install r-base-dev`. In case a newer version is needed, check [here](http://cran.r-project.org/bin/linux/ubuntu/README).

Then [RStudio](http://www.rstudio.com/) is a good IDE for all platforms. The latest beta version is required to use `rmarkdown` and `shiny` from the menu.

Note that to create PDFs from *RStudio* in Ubuntu you also need `texlive-latex-extras` and `texlive-fonts-recommended`.

# Packages

There is no standard dependency manager that comes with R, but there are many solutions:

- Manually install from CRAN: `install.packages(NAME)`
- Manually install from github: `devtools::install_github("USER/REPO")` (requires *devtools*)
- Automatically with [rbundler](https://github.com/opower/rbundler)
- Automatically with [packrat](http://rstudio.github.io/packrat/)

Note that automatic dependency managers also track package versions for ensuring reproducibility and compatibility. The downside is that they store source and binaries under the project's directory.

# Content creation

With [R Markdown](http://rmarkdown.rstudio.com/), it's possible to create HTML documents, slides for presentations and PDFs for reports directly from R. An advantage is to work with the real data, without need to export plots and import them in LaTeX or other programs (as well as keeping them up to date).

Another interesting option is to create interactive reports in the form of web pages or slides, also generated from R code without any HTML or Javascript. See [shiny](http://www.rstudio.com/shiny/).

# Tips

- Use factors for qualitative (ordered or unordered) variables. The order is followed in plots.
- Learn R's formula syntax as soon as possible: it's used for models, plots, etc.
- Make sure your data is in the [appropriate format](http://vita.had.co.nz/papers/tidy-data.html) for these tools.
- Extracting information from the output of R functions is hard because of the list format. To fix this, try [broom](https://github.com/dgrtwo/broom).
- Don't use base graphics, go for [lattice](http://science.nature.nps.gov/im/datamgmt/statistics/r/graphics/lattice.cfm) or [ggplot](http://www.r-bloggers.com/ggplot2-cheatsheet-for-visualizing-distributions/).
- A better interface for transforming data is `plyr`, and for data frames [dplyr](https://github.com/hadley/dplyr).
- There are better alternatives for `summary` in [additional packages](http://www.statmethods.net/stats/descriptives.html).
- Use `reshape2` to convert factor variables to columns or vice versa. See this [tutorial](http://seananderson.ca/2013/10/19/reshape.html).
- Use `pander` to render tables when using `rmarkdown`.
- Use the pipe operators (`%.%` from `dplyr`, or `%>%` from [megrittr](https://github.com/smbache/magrittr)). See this [example](http://stackoverflow.com/questions/22314680/how-to-use-the-operator-in-r).
- A faster data frame implementation is [data.table](http://blog.yhathq.com/posts/fast-summary-statistics-with-data-dot-table.html), still compatible with `dplyr`.
- A good classification and regression wrapper/tool package that uses parallelization is [caret](http://topepo.github.io/caret/).

# Recommended packages

## Programming

- testthat: testing framework

### Paradigms
- R's OOP system uses generic functions not part of any class that dispatch on their arguments, and classes are just records with data (immutable and with copy semantics).
- For traditional (possibly mutable) OOP in R, check [Reference classes](http://adv-r.had.co.nz/OO-essentials.html).
- For prototype based OOP check [proto](http://code.google.com/p/r-proto/wiki/Overview).

### Optimization
- To use available parallelism, try `doMC` (for multicore) and `doMPI` (for many nodes, distributed). They have to be enabled with `registerDoMC(cores=8)`, and used with `%dopar%` or other functions (see `parallel`).
- [aprof](https://github.com/MarcoDVisser/aprof): Amdahl's profiler, directed optimization made easy
- proftools: Profile Output Processing Tools for R
- [profr](https://github.com/hadley/profr): An alternative display for profiling information
- timeit: Easy profiling of R functions

## Graphics

### Plots
- GGally: additional graphics using `ggplot`, like advanced scatter plot matrix
- plotrix: many additional plots, like radial/spider
- aplpack: special plots like stem.leaf, bagplot, faces, spin3R, plotsummary, plothulls
- pheatmap: better heatmap for visualizing matrices, also with dendrogram
- [ggtern](http://www.ggtern.com/): ternary diagrams for ggplot2
- [tabplot](https://github.com/mtennekes/tabplot): a visualization of large datasets, numerical and categorical

### Specific
- [ggbiplot](https://github.com/vqv/ggbiplot): PCA biplot for ggplot2
- NeatMap: Non-clustered heatmap alternatives
- heplots: Visualizing Hypothesis Tests in Multivariate Linear Models
- [corrplot](http://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html): visualizing correlation matrices and confidence intervals

### Utilities
- gridExtra, gtable: arrange `lattice` and `ggplot` plots in a table
- [directlabels](http://directlabels.r-forge.r-project.org/): direct labels for multicolor plots in lattice or ggplot2
- [ggsubplot](https://github.com/garrettgman/ggsubplot): explore complex data by embedding `ggplot` plots
- readbitmap, pixmap: read different image files (jpg, png, bmp, etc) with the same function
- colorspace, munsell: better color systems for plot output (HUSL is missing)
- abind: merging multidimensional arrays (such as image channels)

## Models

- Both `ggplot` and `lattice` support adding regression lines and intervals, but `visreg` provides generic functions to plot a fitted model.

### Similarity

- [dendextend](https://github.com/talgalili/dendextend/): Extending R's dendrogram functionality
- dendroextras: Extra functions to cut, label and colour dendrogram clusters
- [ggdendro](https://github.com/andrie/ggdendro): Tools to extract dendrogram plot data for use with `ggplot`
- proxy: collection of Distance and Similarity Measures
- stringdist: Approximate string matching and string distance functions

### MDS and SOM

This is similar to dimensionality reduction, but works with a distance matrix instead of the vectors in the original space.

- kohonen: Supervised and unsupervised self-organising maps
- popsom: Self-Organizing Maps With Population Based Convergence Criterion
- somplot: Visualisation of hexagonal Kohonen maps
- smacof: Multidimensional Scaling in R
- MDSGUI: A GUI for interactive MDS in R

### Categorical Data

- ca: Correspondence Analysis
- anacor: Simple and Canonical Correspondence Analysis, supports missing values
- vcd, vcdExtra: plots inspired from *Visualizing Categorical Data* book
- extracat: Categorical Data Analysis and Visualization
- ggparallel: Variations of Parallel Coordinate Plots for Categorical Data

### Misc

- lda: Linear Discriminant Analysis, from `MASS`
- svm: Support Vector Machines, from `e1701`
- MCA: Multiple Correspondence Analysis, from [FactoMineR](http://factominer.free.fr/index.html), also includes an R commander GUI
- likelihood.test: G-test of independence, from `Deducer`
- klaR: Classification and visualization
- candisc: visualization of generalized discriminant and correlation analysis

# Resources

## General

- [Quick-R Guide](http://www.statmethods.net/), and the expanded book [R in Action (2011)](http://www.amazon.com/R-Action-Robert-Kabacoff/dp/1935182390)
- Free book and presentation [Practical tools for exploring data and models](http://had.co.nz/thesis/), from the author of `ggplot2`
- Book [Reproducible Research with R and RStudio (2013)](http://www.amazon.com/Reproducible-Research-RStudio-Chapman-Series/dp/1466572841), a bit outdated
- Book [Advanced R Programming (2014)](http://adv-r.had.co.nz/), on-line draft

## Specific

- [10 R Packages I wish I knew about earlier](http://blog.yhathq.com/posts/10-R-packages-I-wish-I-knew-about-earlier.html)
- [Gaston Sanchez's R Packages](http://gastonsanchez.com/software/)
- [Multiple Correspondence Analysis](http://rstudio-pubs-static.s3.amazonaws.com/2120_cfbb7161b23e494ea47707f5a12032f1.html)
- [Computing and Visualizing LDA in R](http://tgmstat.wordpress.com/2014/01/15/computing-and-visualizing-lda-in-r/)
- [Computing and Visualizing PCA in R](http://tgmstat.wordpress.com/2013/11/28/computing-and-visualizing-pca-in-r/)
- [LDA example with clustering](http://web.bahcesehir.edu.tr/atabey_kaygun/other/lda.html)
- [How to list all available generic R functions](http://stackoverflow.com/questions/15803154/see-which-s3-generic-methods-are-available-in-environment)
- [5 Ways to do 2D histograms in R](http://www.r-bloggers.com/5-ways-to-do-2d-histograms-in-r/)
- [G-test of independence](http://www.biostathandbook.com/gtestind.html)
- [Log-linear analysis](http://ww2.coastal.edu/kingw/statistics/R-tutorials/loglin.html): for contingency table models